development:
  adapter: mysql2
  encoding: utf8
  database: valentinos_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  
  test:
    adapter: sqlite3
    database: db/test.sqlite3
    pool: 5
    timeout: 5000

  production:
      adapter: mysql2
      database: valentinos_production
      host: 127.0.0.1
      username: root
      password: Fr1day34